CREATE DATABASE Psi;
USE Psi;

CREATE TABLE Cuisiniers (
	ID_CUISINIER INT PRIMARY KEY,
    MDP INT,
    NOM VARCHAR(100),
    PRENOM VARCHAR(100),
    ADRESSE VARCHAR(100),
    VILLE VARCHAR(100),
    NUM_TEL CHAR(10),
    ADRESSE_MAIL VARCHAR(100)
);

CREATE TABLE Plats (
	ID_PLAT INT PRIMARY KEY,
    TYPE_DE_CUISINE VARCHAR(100),
    TYPE_DE_PLAT VARCHAR(100),
    STOCK INT,
    NB_PERSONNE INT,
    PRIX decimal(5,2),
    DATE_FABRICATION DATE,
    DATE_PEREMPTION DATE,
    REGIME_ALIMENTAIRE VARCHAR(100),
    INGREDIENTS VARCHAR(100),
    PHOTO binary
);

CREATE TABLE Avis (
	NOTE decimal(2,1) PRIMARY KEY,
    COMMENTAIRE VARCHAR(100)
);

CREATE TABLE Commande (
	ID_COMMANDE INT PRIMARY KEY,
    SOUS_TOTAL DECIMAL(5,2),
    STATUT VARCHAR(100),
    PREVISION_ARRIVEE datetime
);

CREATE TABLE Livraison (
	ADRESSE_DE_LIVRAISON VARCHAR(100)
);

CREATE TABLE Client (
	ID_CLIENT INT PRIMARY KEY,
    MDP int
);

CREATE TABLE Entreprise (
	SIRET INT PRIMARY KEY,
    NOM_ENTREPRISE VARCHAR(100),
    NOM_REFERENT VARCHAR(100),
    NUM_TEL_REFERENT CHAR(10),
    ADRESSE VARCHAR(100),
    VILLE VARCHAR(100)
);

CREATE TABLE Particulier (
	NOM VARCHAR(100) PRIMARY KEY,
    PRENOM VARCHAR(100),
    VILLE VARCHAR(100),
    NUM_TEL CHAR(10)
);
    
	